### PR TITLE
Leverage new default url redirects

### PR DESCRIPTION
**Pull request by SokratisVidros**

### CODE REVIEW

**Comment by nachoiacovino** [comment]
Just tested this on the branch, if I tried going to /user when I'm signed out, I'm redirected to my sign-in URL, in my case https://accounts.16n8f.sn3je.lcl.dev/sign-in, is this expected behavior? Or is it because I have an old Vercel instance?

**Comment by SokratisVidros** [comment]
> Just tested this on the branch, if I tried going to /user when I'm signed out, I'm redirected to my sign-in URL, in my case https://accounts.16n8f.sn3je.lcl.dev/sign-in, is this expected behavior? Or is it because I have an old Vercel instance?

It's because it's an old Vercel application.

**Comment by nachoiacovino** [comment]
> > Just tested this on the branch, if I tried going to /user when I'm signed out, I'm redirected to my sign-in URL, in my case https://accounts.16n8f.sn3je.lcl.dev/sign-in, is this expected behavior? Or is it because I have an old Vercel instance?
> 
> It's because it's an old Vercel application.

Just tried with a new instance, works fine! Thank you.

**Review by nachoiacovino — APPROVED** [review]
Just tried with a new instance, works fine!

**Comment by colinclerk** [comment]
To confirm - this works because the Deploy Button has `&external-id=starter`?

**Comment by SokratisVidros** [comment]
> To confirm - this works because the Deploy Button has `&external-id=starter`?

Yes

**Comment by colinclerk** [comment]
Missed these:
https://github.com/clerkinc/clerk-nextjs-starter/blob/948b7ea8e31baa819f4340e343591d9f536e6415/components/Header.js#L27

**Pull request merged**
